[tool.poetry]
name = "py_check"
version = "0.1.0"
description = ""
authors = ["Jake Williamson"]

[tool.poetry.dependencies]
python = "^3.10.8"

[tool.poetry.dev-dependencies]
pytest = "7.2.0"
pylint = "3.0.2"
coverage = "7.0.2"
mypy = "0.991"
black = "22.12.0"
flake8 = "6.0.0"

[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"