[tool.poetry]
name = "py_check"
version = "0.1.0"
description = ""
authors = ["Jake Williamson"]

[tool.poetry.dependencies]
python = "^3.10.8"

[tool.poetry.dev-dependencies]
pytest = "7.4.3"
pylint = "3.0.2"
coverage = "7.3.2"
mypy = "1.6.1"
black = "23.10.1"
flake8 = "6.1.0"

[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"