[tool.poetry]
name = "py_check"
version = "0.1.0"
description = ""
authors = ["Jake Williamson"]

[tool.poetry.dependencies]
python = "^3.10.8"

[tool.poetry.dev-dependencies]
pytest = "8.3.2"
pylint = "3.2.2"
coverage = "7.6.1"
mypy = "1.13.0"
black = "24.8.0"
flake8 = "7.1.0"

[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"