on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  verify-job:
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/devcontainers/universal:focal
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Init and Verify Languages
        run: |
          for dir in */
          do    
              make init -C $dir
              make verify -C $dir
          done

